Description: oneclick automation

Parameters: 
  Instancetypeparameter: 
    Type: String
    Default: t2.micro
    
    AllowedValues: 
      - t2.micro
Resources:
  oneclickinstance: 
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-080e1f13689e07408
      InstanceType: !Ref Instancetypeparameter
      KeyName: nvirginia
      Tags:
        - Key: Name
          Value: oneclickinstance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref oneclickinstance
      
  oneclickvpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
     
  INTERNETGATEWAY: 
    Type: AWS::EC2::InternetGateway
    
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref oneclickvpc 
      InternetGatewayId: !Ref INTERNETGATEWAY
  oneclicksubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      VpcId: !Ref oneclickvpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a

      
  oneclickroutetable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref oneclickvpc
      
  oneclickroute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref oneclickroutetable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref INTERNETGATEWAY
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref oneclicksubnet
      RouteTableId: !Ref oneclickroutetable    
